import json
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: generate_pptx.py <manifest.json> <output.pptx>", file=sys.stderr)
        return 1

    manifest_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    bullet_slide_layout = prs.slide_layouts[1]

    title_slide = prs.slides.add_slide(title_slide_layout)
    title_slide.shapes.title.text = manifest.get("title", "Research Deck")
    title_slide.placeholders[1].text = manifest.get("subtitle", "Generated by ReAgent")

    for slide_data in manifest.get("slides", []):
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = slide_data.get("title", "Slide")
        body = slide.placeholders[1].text_frame
        body.clear()

        bullets = slide_data.get("bullets", [])
        if bullets:
            first = body.paragraphs[0]
            first.text = bullets[0]
            first.level = 0
            first.font.size = Pt(20)
            for bullet in bullets[1:]:
                paragraph = body.add_paragraph()
                paragraph.text = bullet
                paragraph.level = 0
                paragraph.font.size = Pt(18)

        image_path = slide_data.get("image_path")
        if image_path:
            image_file = Path(image_path)
            if image_file.exists():
                slide.shapes.add_picture(str(image_file), Inches(6.2), Inches(1.2), width=Inches(3.0))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
